#!/bin/sh

# When debugging, we might need it to not die at the first hurdle.
# set +e

# Ensure we see stdout and stderr in the logs
exec 2>&1

# Make sure our app can find the JRE
export JAVA_HOME={{pkgPathFor "core/corretto8"}}

# Check if we need to initialise the work directory
if [ ! -d "/hab/svc/nexus/data/sonatype-work" ] ; then
  echo "Initializing Sonatype Work Directory"
  mkdir -p /hab/svc/nexus/data/sonatype-work/prefs
  cp -RT {{pkg.path}}/sonatype-work /hab/svc/nexus/data/sonatype-work
fi

if [ ! -d "/hab/svc/nexus/data/sonatype-work/nexus3/etc" ] ; then
  mkdir -p /hab/svc/nexus/data/sonatype-work/nexus3/etc
fi

if [ -f "/hab/svc/nexus/data/sonatype-work/nexus3/etc/nexus.properties" ] ; then
  echo "Replacing old Nexus customisations"
  unlink /hab/svc/nexus/data/sonatype-work/nexus3/etc/nexus.properties
fi

echo "Connecting dynamic Nexus customisations"
ln -s /hab/svc/nexus/config/nexus.properties /hab/svc/nexus/data/sonatype-work/nexus3/etc/nexus.properties

echo "Starting Nexus"
exec nexus run
